version: '3.3'

services:
  base:
    build:
      context: ../asterisk
      dockerfile: Dockerfile
    image: mybaseimage:latest
  freepbx:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: flaviostutz/freepbx
    depends_on:
      - base     
    ports:
      - 8080:80
      - 5060:5060/udp
      - 5160:5160/udp
      - 3306:3306
      - 18000-18100:18000-18100/udp
    # network_mode: host
    privileged: true
    restart: always
    environment:
      - MARIADB_REMOTE_ROOT_PASSWORD=admin123
      - ADMIN_PASSWORD=admin123
      - DISABLE_SIGNATURE_CHECK=true
      - USE_CHAN_SIP=true
      - FAIL2BAN_ENABLE=true
      - FAIL2BAN_FINDTIME=30
      - FAIL2BAN_MAXRETRY=10
      - FAIL2BAN_BANTIME=10
    volumes:
      - backup:/backup
      - recordings:/var/spool/asterisk/monitor
      - certificates:/etc/asterisk/keys
      - ./startup.sh:/startup.sh
      - ./apply-initial-configs.sh:/apply-initial-configs.sh
      - ./backup.sh:/backup.sh
      - ./delete-old-recordings.sh:/delete-old-recordings.sh
      - ./basic-config.tar.gz:/basic-config.tar.gz
      - ./generate-sha1.php:/generate-sha1.php
      - ./index.html:/var/www/html/index.html
      - ./freepbx_chown.conf:/etc/asterisk/freepbx_chown.conf
      #- ./fail2ban-jail.conf:/etc/fail2ban/jail.d/fail2ban-jail.conf
      #- ./jail.local:/etc/fail2ban/jail.local

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - "9292:8080"

volumes:
  backup:
  recordings:
  certificates:
